root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main"
cmd = "go build -o tmp/main ."
full_bin = "./tmp/main"
args_bin = []
delay = 1000
exclude_dir = ["tmp", "vendor", "node_modules"]
include_ext = ["go", "env"]

[log]
time = true

[screen]
clear = true
