services:
  golang-backend:
    build: .
    container_name: mahad_backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - mahad_network

networks:
  mahad_network:
