services:
  mtadigital_backend:
    build: .
    container_name: mtadigital_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - mahad_network

networks:
  mahad_network:
